kind: Service
apiVersion: v1
metadata:
  labels:
    app: jere-unitykube
  name: jere-unitykube
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: jere-unitykube
